### ISSUE TITLE
Missing libgcrypt.so.11 

### ISSUE THREAD

**Issue by jkawamoto** [storj/java-libstorj#24]
I got this error:

```
[03:33:42.331] [verbose] [main] DEBUG net.harawata.appdirs.AppDirsFactory - os.name linux is resolved to *nix
[03:33:42.332] [verbose] SLF4J: A number (1) of logging calls during the initialization phase have been intercepted and are
[03:33:42.333] [verbose] SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
[03:33:42.334] [verbose] SLF4J: See also http://www.slf4j.org/codes.html#replay
[03:33:42.363] [verbose] Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/.mount_Goobox7MTPMb/resources/app/goobox-sync-storj/libstorj-java.so: libgcrypt.so.11: cannot open shared object file: No such file or directory
[03:33:42.365] [verbose] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[03:33:42.366] [verbose] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
[03:33:42.367] [verbose] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
[03:33:42.368] [verbose] 	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
[03:33:42.368] [verbose] 	at java.lang.System.loadLibrary(System.java:1122)
[03:33:42.369] [verbose] 	at io.storj.libstorj.Storj.loadLibrary(Storj.java:425)
[03:33:42.370] [verbose] 	at io.storj.libstorj.Storj.<clinit>(Storj.java:409)
[03:33:42.371] [verbose] 	at io.goobox.sync.storj.App.init(App.java:150)
[03:33:42.372] [verbose] 	at io.goobox.sync.storj.App.main(App.java:106)
```

Actually `java-libstorj-0.8.3-linux64-so.tar.gz` doesn't have `libgcrypt.so.11`. Does the archive file miss the library file or do we need to install some packages by ourselves?

**Comment by jasonwee** [comment]
I have provided my input [here](https://github.com/GooBox/goobox-sync-storj/issues/127#issuecomment-410141943) . When user click on the installer button, it should automatic pull in the dependency library.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
